version: '3'
services:
  portal:
    ports:
      - "8080:8080"
    image: "icdocsoc/portal:aws"
    volumes:
      - /portal/sponsors:/portal/sponsors
      - /portal/secure:/portal/secure
      - /portal/logs:/portal/logs
      - /portal/aws:/root/.aws
    command: sudo node app.js
